# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
name: leafcutterITI-py_env
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pip
  - pyranges
  - pandas
  - matplotlib
  - numpy
  - jupyterlab
  - scipy
  - pip:
    - pyro-ppl
  
